name: KiBot automation

on:
  push:
    branches: [ main ]
    paths:
      - "*.sch"
      - "*.kicad_pcb"
      - "*.kicad_pro"

jobs:
  drc:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad10_auto:1.9.1-1_k10.0.4_d13.2
    steps:
      - uses: actions/checkout@v4
      - run: kibot -c config.kibot.yml
