name: Lint

on:
  push:
    branches: [ main ]
    paths: [ ".github/workflows/**" ]
  pull_request:
    paths: [ ".github/workflows/**" ]
  workflow_dispatch:

jobs:
  lint:
    name: kicad-ci
    uses: solar-cooker-UHasselt/kicad-ci/.github/workflows/lint.yml@v1
